MAX_FIELD_LENGTH = 255
MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 150


MAX_SLUG_LENGTH = 20
MIN_SLUG_LENGTH = 3

MAX_UNIT_LENGTH = 20

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 720

MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 32768

SECRET_KEY = "hhz7l-ltdismtf@bzyz+rple7*s*w$jak%whj@(@u0eok^f9k4"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 120000

SHORT_URL_PATH = "s"
MIN_LENGTH_FOR_SHORT_URL = 3
SALT = "mysecret"

FONT_SIZE_HEADER = 16
FONT_SIZE_INGREDIENTS = 10
INDENT_TOP_REGULAR = 40
INDENT_LEFT_REGULAR = 30
INDENT_AFTER_HEADER = 30
INDENT_BETWEEN_INGREDIENTS = 20